### ISSUE TITLE
Can't access the development server

### ISSUE THREAD

**Issue by rasulkireev** [danjac/django-saas-starter#2]
Thank you for creating this cookiecutter. This can be useful to a lot of people.

I'm running into a problem where I can't access the frontend server. I'm not sure that is the best use of words, what I'm trying to say is that when I visit `http://0.0.0.0:8000/`, I get this:

![image](https://user-images.githubusercontent.com/8257474/101285577-05483480-37f7-11eb-8e26-ccc4f55ac5d0.png)

However the mailhog server (`http://0.0.0.0:8025`) works just fine.

I have successfully ran each installation step, with no issues.

Thanks a ton in advance.

**Comment by rasulkireev** [comment]
For additional context, here is what I have when I run `docker-compose up` without the -d flag. 

![image](https://user-images.githubusercontent.com/8257474/101285669-81db1300-37f7-11eb-8fa0-a3baa10c0e94.png)

Including only the django step.

**Comment by danjac** [comment]
Try port 80, not 8000.

**Comment by rasulkireev** [comment]
Yep, this solves the issue! Thanks.
